[IMP] public_budget: diario destino en vista tree transferencias
ingadhoc/odoo-public-administration pull request #493
Opened 2023-07-05 18:28 UTC by pablohmontenegro

Task: 31482

2023-07-05 18:28 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/493).

2023-09-01 19:09 UTC, zaoral requested changes

2023-09-01 19:09 UTC, zaoral commented on public_budget/views/account_payment_views.xml
> +        <field name="arch" type="xml">
account.view_account_payment_tree

2023-09-13 14:03 UTC, zaoral commented
@roboadhoc r+

2023-09-13 14:07 UTC, closed without merging