[FIX] public_budget: error al agregar más de una línea de pago.
ingadhoc/odoo-public-administration pull request #545
Opened 2024-05-13 19:22 UTC by pablohmontenegro

Ticket: 72246

2024-05-13 19:23 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-public-administration/pull/545).

2024-05-14 18:24 UTC, zaoral requested changes

2024-05-14 18:24 UTC, zaoral commented on public_budget/models/account_payment.py
> +                    AccountPayment, destination_accounts_to_compute)._compute_destination_account_id()
```suggestion
            super(
                    AccountPayment, destination_accounts_to_compute)._compute_destination_account_id()
```

2024-05-16 00:34 UTC, zaoral commented
@roboadhoc r+

2024-05-16 00:37 UTC, closed without merging